[package]
name = "summercash"
version = "0.1.0"
authors = ["Dowland Aiello <mitsukomegumii@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
num = "0.2.0"

[lib]
name = "summercash"
path = "src/lib.rs"

[[bin]]
name = "summercash"
path = "src/main.rs"