[package]
name = "summercash"
version = "0.1.0"
authors = ["Dowland Aiello <mitsukomegumii@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
num = "0.2.0"
hex = "0.3.2"
blake2 = "0.8.0"
rand = "0.6.0"
ed25519-dalek = "1.0.0-pre.1"
chrono = "0.4"
time = "0.1.42"
serde = "1.0.98"

[lib]
name = "summercash"
path = "src/lib.rs"

[[bin]]
name = "summercash"
path = "src/main.rs"