on: [push]

jobs:
  build_smcd_image:
    runs:
      using: "docker"
      image: "Dockerfile"
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login
        run: docker login -u SummerCash -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
      - name: Build images
        run: docker build -t docker.pkg.github.com/summercash/rust-summercash/smcd:latest .
      - name: Tag images
        run: docker tag smcd docker.pkg.github.com/summercash/rust-summercash/smcd:latest
      - name: Publish images
        run: docker push docker.pkg.github.com/summercash/rust-summercash
