on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --all
      - name: Test
        run: cargo test --verbose --all
  build_smcd_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Login
        run: docker login -u SummerCash -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
      - name: Build images
        run: docker build -t docker.pkg.github.com/summercash/rust-summercash/smcd:latest .
      - name: Tag images
        run: docker tag smcd docker.pkg.github.com/summercash/rust-summercash/smcd:latest
      - name: Publish images
        run: docker push docker.pkg.github.com/summercash/rust-summercash
