on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --all
      - name: Test
        run: cargo test --verbose --all
  build_smcd_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build images
        run: docker build -t summercash/rust-summercash .
      - name: Tag images
        run: docker tag summercash/rust-summercash summercash/rust-summercash:latest
      - name: Publish images
        run: docker push summercash/rust-summercash:latest
